### ISSUE TITLE
Flashcards with spaced repetition

### ISSUE THREAD

**Issue by AJNOURI** [CloudAssessments/learn-with-anthony-james#5]
The concept of flash cards is a good idea, but the way they are implemented is not very useful (in my opinion). It doesn't remember prior student performences.
What would be great is a spaced repetition system, per-user based, that shows the user each day a number of questions according to prior performance.  
This way the user is regularly (each day/login) presented only with cards that he/she doesn't master yet, other cards are less frequently presented until the user forget them.

This will encourage the user to login regularly to LA and be in touch with courses and contents.

Spaced repetition is very powerfull and I can only imagine the tremendous benefit we LA members could benefit from it.

**Comment by pinehead** [comment]
Thanks,

I'll pass this back to the dev team at LinuxAcademy. This github is really for the learn with anthony course stuff.

**Comment by AJNOURI** [comment]
OK, thanks. 
I close this issue.
